// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from './deno.json' assert { type: 'json' };
import * as $0 from './routes/[planet].tsx';
import * as $1 from './routes/_app.tsx';
import * as $2 from './routes/index.tsx';
import * as $$0 from './islands/Counter.tsx';
import * as $$1 from './islands/Header.tsx';
import * as $$2 from './islands/PlanetTabs.tsx';

const manifest = {
  routes: {
    './routes/[planet].tsx': $0,
    './routes/_app.tsx': $1,
    './routes/index.tsx': $2,
  },
  islands: {
    './islands/Counter.tsx': $$0,
    './islands/Header.tsx': $$1,
    './islands/PlanetTabs.tsx': $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
